### ISSUE TITLE
Error with query for the years 2010 to 2015

### ISSUE THREAD

**Issue by dominicroye** [rafaelmenmell/MorbiditySpainR#4]
I got an error when I try to query the period 2010 to 2015. 

```
Con formatoError in value[[3L]](cond) : 
  Error. No se encuentra el fichero: Error in file(file, "rt"): invalid 'description' argument
md_EMH_2015.txt. Saliendo de la ejecucion...Error. No se encuentra el fichero: Error in file(file, "rt"): invalid 'description' argument
md_EMH_2017.txt. Saliendo de la ejecucion...
```

**Comment by rafaelmenmell** [comment]
Thank you for the feedback. I will try to find the time to fix that issues.

**Comment by rafaelmenmell** [comment]
Can you send me the code you used when you get that error?
I have tried:
`install.packages("devtools")
devtools::install_github("rOpenSpain/MorbiditySpainR")
library(MorbiditySpainR)
data <- GetMorbiData(y1=2015,y2=2015)`

and it worked (although an error was reported, it has no relevance)

**Comment by dominicroye** [comment]
It seems to be a problem when you query more than the specific year 2015. 


`data <- GetMorbiData(y1=2014,y2=2015)`

**Comment by rafaelmenmell** [comment]
I don't know, it works fine for me.
Send me the full code and the sessionInfo() and I'll check again.

**Comment by dominicroye** [comment]
I just updated all my packages and now it seems to work fine. I cannot say which package provoked the issue.  (anyway, i'm also now member of rOpenSpain, see Slack, if you like, we can discuss some ideas for the package)

**Comment by rafaelmenmell** [comment]
If you are member of rOpenSpain in slack I guess we can switch to spanish.
Yo también soy miembro así que podemos comentar lo que quieras allí, gracias por el interés.
